services:
  redis:
    image: redis:7-alpine
    volumes:
      - ./redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    
  server:
    build: ./server
    depends_on: [redis]
    ports:
      - "8000:8000"

  backup-server:
    build: ./server
    depends_on: [redis]
    ports:
      - "8001:8000" 
      
  client:
    build: ./client
    depends_on: [server]
    ports:
      - "3000:80"





